# pull official base image
FROM node:lts-alpine as builder

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# microfrontend envs
ENV VITE_RECIPES_MICROFRONTEND_URL http://recipes:5001/assets/recipes.js
ENV VITE_MEAL_PLAN_MICROFRONTEND_URL http://meal-plan:5002/assets/mealPlan.js
ENV VITE_SHOPPING_LIST_MICROFRONTEND_URL http://shopping-list:5003/assets/shoppingList.js

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# add app
COPY . ./

EXPOSE 3000

# start app
CMD ["npm", "run", "dev"]

