# pull official base image
FROM node:latest

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# microfrontend envs
ENV VITE_RECIPES_MICROFRONTEND_URL http://localhost:3001/assets/recipes.js
ENV VITE_MEAL_PLAN_MICROFRONTEND_URL http://localhost:3004/assets/mealPlan.js
ENV VITE_SHOPPING_LIST_MICROFRONTEND_URL http://localhost:3003/assets/shoppingList.js

# install app dependencies
COPY . /app
RUN npm install

# add app
COPY . ./

# start app
CMD ["npm", "run", "dev"]

