FROM node:latest as builder
WORKDIR /app
COPY . /app
RUN npm install
RUN npm run build

FROM nginx:alpine

#!/bin/sh

COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy from the builder
COPY --from=builder /app/public /usr/share/nginx/html
COPY --from=builder /app/dist /usr/share/nginx/html/dist

EXPOSE 3001 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]